/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary': '#005149',
        'on-error-container': '#93000a',
        'error': '#ba1a1a',
        'on-secondary-container': '#58657a',
        'on-secondary-fixed-variant': '#3a475b',
        'tertiary-fixed': '#65f9e7',
        'surface-variant': '#e1e2ea',
        'on-tertiary-container': '#5af0de',
        'surface-container-highest': '#e1e2ea',
        'inverse-on-surface': '#eff0f8',
        'primary-fixed': '#d6e3ff',
        'inverse-primary': '#a9c7ff',
        'secondary-container': '#d6e3fc',
        'on-tertiary-fixed': '#00201d',
        'secondary-fixed': '#d6e3fc',
        'on-primary-fixed-variant': '#00468c',
        'background': '#f9f9ff',
        'on-surface-variant': '#424752',
        'inverse-surface': '#2e3037',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed': '#0e1c2e',
        'surface-container': '#ecedf6',
        'on-error': '#ffffff',
        'on-secondary': '#ffffff',
        'surface-tint': '#005db6',
        'error-container': '#ffdad6',
        'primary': '#00478d',
        'on-primary': '#ffffff',
        'on-tertiary-fixed-variant': '#005049',
        'on-primary-container': '#c8daff',
        'surface-container-high': '#e7e8f0',
        'primary-fixed-dim': '#a9c7ff',
        'surface-dim': '#d8dae2',
        'on-surface': '#191c21',
        'on-tertiary': '#ffffff',
        'surface-container-low': '#f2f3fb',
        'secondary': '#525f74',
        'primary-container': '#005eb8',
        'outline-variant': '#c2c6d4',
        'on-background': '#191c21',
        'tertiary-container': '#006b62',
        'surface': '#f9f9ff',
        'outline': '#727783',
        'tertiary-fixed-dim': '#40dccb',
        'surface-bright': '#f9f9ff',
        'secondary-fixed-dim': '#bac7df',
        'on-primary-fixed': '#001b3d',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
